---
- name: Install package yum-utils
  yum:
    name: yum-utils
    state: present

- name: Check PowerTools status
  shell: yum-config-manager --dump PowerTools | grep -q 'enabled = 1'
  changed_when: False
  ignore_errors: True
  register: pt_status
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"

- name: Enabled CentOS PowerTools
  command: yum-config-manager --enable PowerTools
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8" and pt_status.rc != 0
